In [1]:
import numpy as np

In [3]:
x = 40
y = 20

In [4]:
z = x + y

In [5]:
print(z)

60


In [6]:
np.add(x,y)

60

In [7]:
np.subtract(x,y)

20

In [8]:
np.multiply(x,y)

800

In [9]:
np.divide(x,y)

2.0

In [12]:
np.minimum(x,y)

20

In [15]:
np.maximum(x,y)

40

In [18]:
list=[1,2,3,4]
list1=[5,6,7,8]

In [20]:
np.maximum(list,list1)

array([5, 6, 7, 8])

In [21]:
np.minimum(list,list1)

array([1, 2, 3, 4])

In [25]:
a=np.matrix([1,2,3])

In [27]:
np.reshape(a,(3,1))

matrix([[1],
        [2],
        [3]])

In [29]:
b=np.matrix([[1,2,3],[4,5,6]])

In [30]:
b

matrix([[1, 2, 3],
        [4, 5, 6]])

In [31]:
np.reshape(b,(3,2))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [40]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
arr = np.array(30)

In [49]:
print(arr)

30


In [50]:
arr = np.array([2,4,6,8])

In [51]:
arr

array([2, 4, 6, 8])

In [52]:
arr = np.array([[2,4,6],[6,7,8]])

In [53]:
arr

array([[2, 4, 6],
       [6, 7, 8]])

In [121]:
arr =np.array([[[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6]]])

In [122]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [56]:
b= np.array([2,4,6,8])

In [58]:
print(b.ndim)

1


In [59]:
a= np.array([9,2,3,8])

In [64]:
print(a[0], a[1], a[2], a[3])

9 2 3 8


In [65]:
print(a[0]+a[1])

11


In [66]:
print(a[0]-a[3])

1


In [67]:
a= np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [68]:
a= np.array([1,2,3])

In [69]:
print(a.dtype)

int32


In [70]:
a= np.array(['banana','pineapple', 'popaya', 'orange', 'berries'])

In [71]:
print(a[1])

pineapple


In [79]:
a= np.array([1,2,3,4], dtype='i')

In [80]:
print(a)

[1 2 3 4]


In [81]:
b= np.array([1.1,2.2,3.3,4.4], dtype='f')

In [82]:
print(b)

[1.1 2.2 3.3 4.4]


In [124]:
arr=np.array([2,5,7,8,9])

In [127]:
arr.view()
arr[0] = 42

In [128]:
print(arr)

[42  5  7  8  9]


In [129]:
arr.copy()
arr[0]=2

In [130]:
print(arr)

[2 5 7 8 9]


In [92]:
print(arr.shape)

(5,)


In [131]:
list = [1,2,3,4]
for x in list:
    print(x) 

1
2
3
4


In [132]:
print(list[0],list[1],list[2],list[3])

1 2 3 4


In [95]:
a= np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [96]:
arr =np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6 7 8]


In [112]:
arr = np.array([1, 2, 3, 4, 5, 6])
a = np.array_split(arr,6)
print(a)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [115]:
y = np.where(arr==6)
print(y)

(array([5], dtype=int64),)


In [117]:
a= np.array([0,5,2,9,4,8,6])

In [118]:
print(np.sort(a))

[0 2 4 5 6 8 9]


In [138]:
np.random.randint(20, size=(5,3))

array([[16, 11, 14],
       [ 9, 17, 11],
       [13, 12, 14],
       [12, 16, 16],
       [14,  0,  5]])

In [142]:
print(np.__version__)

1.18.1


In [144]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [155]:
print(a[0][-1])

5


In [5]:
x = range(6)
print (x)

range(0, 6)


In [6]:
x = ("apple", "banana", "cherry")
print (x)


('apple', 'banana', 'cherry')
